using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Text;

public static class EfSqlLogger
{
    public static string LogSqlWithParameters<T>(IQueryable<T> query, object parameters = null)
    {
        var sql = query.ToQueryString(); // Cần .NET 5+ và EF Core 5+
        var sb = new StringBuilder();
        sb.AppendLine("===== SQL GENERATED BY EF CORE =====");
        sb.AppendLine(sql);
        if (parameters != null)
        {
            sb.AppendLine("===== PARAMETERS =====");
            var props = parameters.GetType().GetProperties();
            foreach (var prop in props)
            {
                var name = prop.Name;
                var value = prop.GetValue(parameters);
                sb.AppendLine($"{name} = {FormatValue(value)}");
            }
        }
        return sb.ToString();
    }

    private static string FormatValue(object value)
    {
        if (value == null) return "NULL";
        if (value is string s) return $"'{s}'";
        if (value is DateTime dt) return $"'{dt:yyyy-MM-dd HH:mm:ss.fff}'";
        if (value is bool b) return b ? "1" : "0";
        if (value.GetType().IsEnum) return $"{Convert.ToInt32(value)} ({value})";
        return value.ToString();
    }
}
